# DuckDB Demo 🦆

In [4]:
!pip install duckdb #Optional: Colab is already provided

Requirement already satisfied: duckdb in /usr/local/lib/python3.12/dist-packages (1.3.2)

In [2]:
import duckdb

Connect to DuckDB or create a new connection

In [3]:
connection = duckdb.connect()

# Output format: the format of the output data

This example in this section is adapted from: https://www.datacamp.com/blog/an-introduction-to-duckdb-what-is-it-and-why-should-you-use-it

`show()` will display the results in a table format

In [5]:
duckdb.sql('SELECT 42').show()

┌───────┐
│  42   │
│ int32 │
├───────┤
│    42 │
└───────┘

`fetchall()` returns the results as a list of tuples

In [6]:
results = duckdb.sql('SELECT 42').fetchall()
print(results)

[(42,)]

In [7]:
type(results)

list

In [8]:
results_df = duckdb.sql('SELECT 42').df()
print(results)

[(42,)]

In [9]:
type(results_df)

pandas.core.frame.DataFrame

# Read files: Let’s read some files

Use sample data from this Git repository: https://github.com/Teradata/kylo/tree/master/samples/sample-data

Then select raw data, for example:

**CSV:** userdata1.csv - userdata5.csv
https://raw.githubusercontent.com/Teradata/kylo/master/samples/sample-data/csv/userdata1.csv

**Parquet:** userdata1.parquet - userdata5.parquet
https://raw.githubusercontent.com/Teradata/kylo/master/samples/sample-data/parquet/userdata1.parquet

**JSON:** books1.json, colors.json
https://raw.githubusercontent.com/Teradata/kylo/master/samples/sample-data/json/books1.json

In [10]:
user1 = duckdb.read_csv('https://raw.githubusercontent.com/Teradata/kylo/master/samples/sample-data/csv/userdata1.csv')
user2 = duckdb.read_parquet('https://raw.githubusercontent.com/Teradata/kylo/master/samples/sample-data/parquet/userdata2.parquet')
books = duckdb.read_json('https://raw.githubusercontent.com/Teradata/kylo/master/samples/sample-data/json/books1.json')
colors = duckdb.read_json('https://raw.githubusercontent.com/Teradata/kylo/master/samples/sample-data/json/colors.json')

# Try querying the data

In [12]:
duckdb.sql('SELECT * FROM user1 limit 10')     # directly query a CSV file

┌──────────────────────────┬───────┬────────────┬───────────┬──────────────────────────┬─────────────┬────────────────┬──────────────────┬────────────────────────┬────────────┬───────────┬──────────────────────────┬──────────┐
│    registration_dttm     │  id   │ first_name │ last_name │          email           │   gender    │   ip_address   │        cc        │        country         │ birthdate  │  salary   │          title           │ comments │
│ timestamp with time zone │ int64 │  varchar   │  varchar  │         varchar          │   varchar   │    varchar     │     varchar      │        varchar         │    date    │  double   │         varchar          │ varchar  │
├──────────────────────────┼───────┼────────────┼───────────┼──────────────────────────┼─────────────┼────────────────┼──────────────────┼────────────────────────┼────────────┼───────────┼──────────────────────────┼──────────┤
│ 2016-02-03 07:55:29+00   │     1 │ Amanda     │ Jordan    │ ajordan0@com.com         │ Female      │ 1.197.201.2    │ 6759521864920116 │ Indonesia              │ 1971-03-08 │  49756.53 │ Internal Auditor         │ 1E+02    │
│ 2016-02-03 17:04:03+00   │     2 │ Albert     │ Freeman   │ afreeman1@is.gd          │ Male        │ 218.111.175.34 │ NULL             │ Canada                 │ 1968-01-16 │ 150280.17 │ Accountant IV            │ NULL     │
│ 2016-02-03 01:09:31+00   │     3 │ Evelyn     │ Morgan    │ emorgan2@altervista.org  │ Female      │ 7.161.136.94   │ 6767119071901597 │ Russia                 │ 1960-02-01 │ 144972.51 │ Structural Engineer      │ NULL     │
│ 2016-02-03 12:36:21+00   │     4 │ Denise     │ Riley     │ driley3@gmpg.org         │ Female      │ 140.35.109.83  │ 3576031598965625 │ China                  │ 1997-04-08 │  90263.05 │ Senior Cost Accountant   │ NULL     │
│ 2016-02-03 05:05:31+00   │     5 │ Carlos     │ Burns     │ cburns4@miitbeian.gov.cn │ NULL        │ 169.113.235.40 │ 5602256255204850 │ South Africa           │ NULL       │      NULL │ NULL                     │ NULL     │
│ 2016-02-03 07:22:34+00   │     6 │ Kathryn    │ White     │ kwhite5@google.com       │ Transgender │ 195.131.81.179 │ 3583136326049310 │ Indonesia              │ 1983-02-25 │  69227.11 │ Account Executive        │ NULL     │
│ 2016-02-03 08:33:08+00   │     7 │ Samuel     │ Holmes    │ sholmes6@foxnews.com     │ Unknown     │ 232.234.81.197 │ 3582641366974690 │ Portugal               │ 1987-12-18 │  14247.62 │ Senior Financial Analyst │ NULL     │
│ 2016-02-03 06:47:06+00   │     8 │ Harry      │ Howell    │ hhowell7@eepurl.com      │ Secret      │ 91.235.51.73   │ NULL             │ Bosnia and Herzegovina │ 1962-03-01 │ 186469.43 │ Web Developer IV         │ NULL     │
│ 2016-02-03 03:52:53+00   │     9 │ Jose       │ Foster    │ jfoster8@yelp.com        │ Obvious     │ 132.31.53.61   │ NULL             │ South Korea            │ 1992-03-27 │ 231067.84 │ Software Test Engineer I │ 1E+02    │
│ 2016-02-03 18:29:47+00   │    10 │ Emily      │ Stewart   │ estewart9@opensource.org │ Female      │ 143.28.251.245 │ 3574254110301671 │ Nigeria                │ 1997-01-28 │  27234.28 │ Health Coach IV          │ NULL     │
├──────────────────────────┴───────┴────────────┴───────────┴──────────────────────────┴─────────────┴────────────────┴──────────────────┴────────────────────────┴────────────┴───────────┴──────────────────────────┴──────────┤
│ 10 rows                                                                                                                                                                                                             13 columns │
└────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

In [11]:
duckdb.sql('SELECT count(*) FROM user1')

┌──────────────┐
│ count_star() │
│    int64     │
├──────────────┤
│         1000 │
└──────────────┘

In [16]:
user1.df()

,registration_dttm,id,first_name,last_name,email,gender,ip_address,cc,country,birthdate,salary,title,comments
0,2016-02-03 07:55:29+00:00,1,Amanda,Jordan,ajordan0@com.com,Female,1.197.201.2,6759521864920116,Indonesia,1971-03-08,49756.53,Internal Auditor,1E+02
1,2016-02-03 17:04:03+00:00,2,Albert,Freeman,afreeman1@is.gd,Male,218.111.175.34,None,Canada,1968-01-16,150280.17,Accountant IV,None
2,2016-02-03 01:09:31+00:00,3,Evelyn,Morgan,emorgan2@altervista.org,Female,7.161.136.94,6767119071901597,Russia,1960-02-01,144972.51,Structural Engineer,None
3,2016-02-03 12:36:21+00:00,4,Denise,Riley,driley3@gmpg.org,Female,140.35.109.83,3576031598965625,China,1997-04-08,90263.05,Senior Cost Accountant,None
4,2016-02-03 05:05:31+00:00,5,Carlos,Burns,cburns4@miitbeian.gov.cn,None,169.113.235.40,5602256255204850,South Africa,NaT,NaN,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,2016-02-03 10:30:59+00:00,996,Dennis,Harris,dharrisrn@eepurl.com,Male,178.180.111.236,374288806662929,Greece,1965-07-08,263399.54,Editor,None
996,2016-02-03 17:16:53+00:00,997,Gloria,Hamilton,ghamiltonro@rambler.ru,Female,71.50.39.137,None,China,1975-04-22,83183.54,VP Product Management,None
997,2016-02-03 05:02:20+00:00,998,Nancy,Morris,nmorrisrp@ask.com,None,6.188.121.221,3553564071014997,Sweden,1979-05-01,NaN,Junior Executive,None
998,2016-02-03 02:41:32+00:00,999,Annie,Daniels,adanielsrq@squidoo.com,Female,97.221.132.35,30424803513734,China,1991-10-09,18433.85,Editor,​
999,2016-02-03 09:52:18+00:00,1000,Julie,Meyer,jmeyerrr@flavors.me,Female,217.1.147.132,374288099198540,China,NaT,222561.13,None,None

In [17]:
duckdb.sql("SELECT avg(salary) from user1 where user1.country = 'China'")

┌────────────────────┐
│    avg(salary)     │
│       double       │
├────────────────────┤
│ 157365.24564971743 │
└────────────────────┘

In [15]:
user2

┌─────────────────────┬───────┬────────────┬───────────┬───────────────────────────┬─────────┬─────────────────┬──────────────────┬──────────────┬────────────┬───────────┬──────────────────────────┬───────────────────────────────┐
│  registration_dttm  │  id   │ first_name │ last_name │           email           │ gender  │   ip_address    │        cc        │   country    │ birthdate  │  salary   │          title           │           comments            │
│      timestamp      │ int32 │  varchar   │  varchar  │          varchar          │ varchar │     varchar     │     varchar      │   varchar    │  varchar   │  double   │         varchar          │            varchar            │
├─────────────────────┼───────┼────────────┼───────────┼───────────────────────────┼─────────┼─────────────────┼──────────────────┼──────────────┼────────────┼───────────┼──────────────────────────┼───────────────────────────────┤
│ 2016-02-03 13:36:39 │     1 │ Donald     │ Lewis     │ dlewis0@clickbank.net     │ Male    │ 102.22.124.20   │                  │ Indonesia    │ 7/9/1972   │ 140249.37 │ Senior Financial Analyst │                               │
│ 2016-02-03 00:22:28 │     2 │ Walter     │ Collins   │ wcollins1@bloglovin.com   │ Male    │ 247.28.26.93    │ 3587726269478025 │ China        │            │      NULL │                          │                               │
│ 2016-02-03 18:29:04 │     3 │ Michelle   │ Henderson │ mhenderson2@geocities.jp  │ Female  │ 193.68.146.150  │                  │ France       │ 1/15/1964  │ 236219.26 │ Teacher                  │                               │
│ 2016-02-03 13:42:19 │     4 │ Lori       │ Hudson    │ lhudson3@dion.ne.jp       │         │ 34.252.168.48   │ 3568840151595649 │ Russia       │ 4/22/1988  │      NULL │ Nuclear Power Engineer   │                               │
│ 2016-02-03 00:15:29 │     5 │ Howard     │ Miller    │ hmiller4@fema.gov         │ Male    │ 103.193.150.230 │ 3583473261055014 │ France       │ 11/26/1998 │  50210.02 │ Senior Editor            │                               │
│ 2016-02-03 10:49:07 │     6 │ Frances    │ Adams     │ fadams5@123-reg.co.uk     │ Female  │ 106.196.106.93  │                  │ Russia       │ 3/27/1997  │  82175.77 │ Account Coordinator      │                               │
│ 2016-02-03 19:44:12 │  NULL │ Steven     │ Hanson    │ shanson6@cisco.com        │ Male    │ 234.130.172.185 │ 3550842607768119 │ Indonesia    │            │ 129582.61 │                          │                               │
│ 2016-02-03 08:11:34 │     8 │ Louis      │ Simmons   │ lsimmons7@icio.us         │ Male    │ 18.69.80.15     │                  │ China        │ 6/1/1992   │  90744.86 │ Product Engineer         │                               │
│ 2016-02-03 23:56:51 │     9 │ Keith      │ Parker    │ kparker8@amazonaws.com    │ Male    │ 108.205.40.64   │                  │ Guadeloupe   │ 12/30/1992 │   60618.9 │ Developer II             │                               │
│ 2016-02-03 07:47:29 │    10 │ Wanda      │ Walker    │ wwalker9@latimes.com      │ Female  │ 246.214.98.78   │ 3539421569669478 │ Portugal     │            │ 137664.53 │                          │                               │
│          ·          │     · │  ·         │   ·       │        ·                  │   ·     │       ·         │        ·         │    ·         │     ·      │        ·  │            ·             │               ·               │
│          ·          │     · │  ·         │   ·       │        ·                  │   ·     │       ·         │        ·         │    ·         │     ·      │        ·  │            ·             │               ·               │
│          ·          │     · │  ·         │   ·       │        ·                  │   ·     │       ·         │        ·         │    ·         │     ·      │        ·  │            ·             │               ·               │
│ 2016-02-03 02:39:55 │   991 │ Amy        │ James     │ ajamesri@mlb.com          │         │ 249.242.29.163  │ 3542908406153406 │ Burkina Faso │ 11/9/1982  │      NULL │ Systems Administrator I  │                               │
│ 2016-02-03 03:55:45 │   992 │ Joyce      │ Bell      │ jbellrj@wordpress.com     │ Female  │ 165.183.250.52  │                  │ China        │ 7/31/1960  │  50526.45 │ Graphic Designer         │                               │
│ 2016-02-03 01:06:44 │   993 │ Christina  │ Hayes     │ chayesrk@xing.com         │ Female  │ 199.58.20.93    │                  │ North Korea  │ 10/30/1967 │  121659.5 │ Librarian                │                               │
│ 2016-02-03 02:08:01 │   994 │ Earl       │ Butler    │ ebutlerrl@posterous.com   │         │ 209.157.200.68  │ 3543989857454146 │ Egypt        │ 2/2/1981   │      NULL │ Speech Pathologist       │ ✋🏿 💪🏿 👐🏿 🙌🏿 👏🏿 🙏🏿 │
│ 2016-02-03 16:26:28 │   995 │            │ Rivera    │                           │ Male    │ 64.31.122.188   │                  │ Botswana     │ 2/17/1980  │ 180088.74 │ Senior Editor            │                               │
│ 2016-02-03 13:36:49 │   996 │ Carol      │ Warren    │ cwarrenrn@geocities.jp    │ Female  │ 71.7.191.213    │                  │ China        │            │ 185421.82 │                          │ "                             │
│ 2016-02-03 04:39:01 │   997 │ Helen      │ Fields    │ hfieldsro@comcast.net     │ Female  │ 164.190.97.183  │                  │ Malaysia     │            │ 279671.68 │                          │                               │
│ 2016-02-03 00:33:54 │   998 │ Stephanie  │ Sims      │ ssimsrp@newyorker.com     │ Female  │ 135.66.68.181   │ 3548125808139842 │ Poland       │            │ 112275.78 │                          │                               │
│ 2016-02-03 00:15:08 │   999 │ Marie      │ Medina    │ mmedinarq@thetimes.co.uk  │ Female  │ 223.83.175.211  │                  │ Kazakhstan   │ 3/25/1969  │  53564.76 │ Speech Pathologist       │                               │
│ 2016-02-03 00:53:53 │  1000 │ Alice      │ Peterson  │ apetersonrr@parallels.com │ Female  │ 244.89.94.58    │ 5602227843485236 │ Nigeria      │            │  239858.7 │                          │                               │
├─────────────────────┴───────┴────────────┴───────────┴───────────────────────────┴─────────┴─────────────────┴──────────────────┴──────────────┴────────────┴───────────┴──────────────────────────┴───────────────────────────────┤
│ 1000 rows (20 shown)                                                                                                                                                                                                    13 columns │
└────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

In [13]:
duckdb.sql('SELECT avg(salary) from user1')

┌────────────────────┐
│    avg(salary)     │
│       double       │
├────────────────────┤
│ 148911.96545551985 │
└────────────────────┘

In [14]:
duckdb.sql('SELECT avg(salary) from user2')

┌────────────────────┐
│    avg(salary)     │
│       double       │
├────────────────────┤
│ 154972.73812765945 │
└────────────────────┘

In [19]:
books

┌────────────────┬───────────┬─────────────────────────────────────────┬────────────────────┬─────────────────────────────────┬────────────┬─────────┬─────────┬────────┬─────────┐
│       id       │    cat    │                  name                   │       author       │            series_t             │ sequence_i │ genre_s │ inStock │ price  │ pages_i │
│    varchar     │  varchar  │                 varchar                 │      varchar       │             varchar             │   int64    │ varchar │ boolean │ double │  int64  │
├────────────────┼───────────┼─────────────────────────────────────────┼────────────────────┼─────────────────────────────────┼────────────┼─────────┼─────────┼────────┼─────────┤
│ 978-0641723445 │ book      │ The Lightning Thief                     │ Rick Riordan       │ Percy Jackson and the Olympians │          1 │ fantasy │ true    │   12.5 │     384 │
│ 978-1423103349 │ paperback │ The Sea of Monsters                     │ Rick Riordan       │ Percy Jackson and the Olympians │          2 │ fantasy │ true    │   6.49 │     304 │
│ 978-1857995879 │ paperback │ Sophie's World : The Greek Philosophers │ Jostein Gaarder    │ NULL                            │          1 │ fantasy │ true    │   3.07 │      64 │
│ 978-1923988177 │ paperback │ Lucene in Action, Second Edition        │ Michael McCandless │ NULL                            │          1 │ IT      │ true    │   30.5 │     475 │
│ 978-1933988077 │ paperback │ Lucene in Action, Second Edition        │ Michael McCandless │ NULL                            │          1 │ IT      │ true    │   30.5 │     475 │
│ 968-1933988177 │ paperback │ Lucene in Action, Second Edition        │ Michael McCandless │ NULL                            │          1 │ IT      │ true    │   30.5 │     300 │
│ 978-2933988077 │ paperback │ Lucene in Action, Second Edition        │ Michael McCandless │ NULL                            │          1 │ IT      │ true    │   30.5 │     475 │
└────────────────┴───────────┴─────────────────────────────────────────┴────────────────────┴─────────────────────────────────┴────────────┴─────────┴─────────┴────────┴─────────┘

In [18]:
duckdb.sql('select * from books').df()

,id,cat,name,author,series_t,sequence_i,genre_s,inStock,price,pages_i
0,978-0641723445,book,The Lightning Thief,Rick Riordan,Percy Jackson and the Olympians,1,fantasy,True,12.50,384
1,978-1423103349,paperback,The Sea of Monsters,Rick Riordan,Percy Jackson and the Olympians,2,fantasy,True,6.49,304
2,978-1857995879,paperback,Sophie's World : The Greek Philosophers,Jostein Gaarder,None,1,fantasy,True,3.07,64
3,978-1923988177,paperback,"Lucene in Action, Second Edition",Michael McCandless,None,1,IT,True,30.50,475
4,978-1933988077,paperback,"Lucene in Action, Second Edition",Michael McCandless,None,1,IT,True,30.50,475
5,968-1933988177,paperback,"Lucene in Action, Second Edition",Michael McCandless,None,1,IT,True,30.50,300
6,978-2933988077,paperback,"Lucene in Action, Second Edition",Michael McCandless,None,1,IT,True,30.50,475

In [20]:
duckdb.sql('SELECT id, cat FROM books')

┌────────────────┬───────────┐
│       id       │    cat    │
│    varchar     │  varchar  │
├────────────────┼───────────┤
│ 978-0641723445 │ book      │
│ 978-1423103349 │ paperback │
│ 978-1857995879 │ paperback │
│ 978-1923988177 │ paperback │
│ 978-1933988077 │ paperback │
│ 968-1933988177 │ paperback │
│ 978-2933988077 │ paperback │
└────────────────┴───────────┘

In [28]:
"""
This function is used to count the number of books for each author
"""
duckdb.sql("""SELECT count(*) as cnt, author
            FROM books
            GROUP BY author
            ORDER BY cnt DESC""")

┌───────┬────────────────────┐
│  cnt  │       author       │
│ int64 │      varchar       │
├───────┼────────────────────┤
│     4 │ Michael McCandless │
│     2 │ Rick Riordan       │
│     1 │ Jostein Gaarder    │
└───────┴────────────────────┘

In [22]:
colors

┌─────────┬──────────┬───────────┬───────────────────────────────────────────┬────────────────────────┐
│  color  │ category │   type    │                   code                    │         other          │
│ varchar │ varchar  │  varchar  │    struct(rgba bigint[], hex varchar)     │ struct("type" varchar) │
├─────────┼──────────┼───────────┼───────────────────────────────────────────┼────────────────────────┤
│ black   │ hue      │ primary   │ {'rgba': [255, 255, 255, 1], 'hex': #000} │ {'type': good}         │
│ white   │ value    │ NULL      │ {'rgba': [0, 0, 0, 1], 'hex': #FFF}       │ {'type': good}         │
│ red     │ hue      │ primary   │ {'rgba': [255, 0, 0, 1], 'hex': #FF0}     │ {'type': ok}           │
│ blue    │ hue      │ primary   │ {'rgba': [0, 0, 255, 1], 'hex': #00F}     │ {'type': good}         │
│ yellow  │ hue      │ primary   │ {'rgba': [255, 255, 0, 1], 'hex': #FF0}   │ {'type': ok}           │
│ green   │ hue      │ secondary │ {'rgba': [0, 255, 0, 1], 'hex': #0F0}     │ {'type': good}         │
└─────────┴──────────┴───────────┴───────────────────────────────────────────┴────────────────────────┘

In [23]:
new_df = books.df()

In [24]:
type(new_df)

pandas.core.frame.DataFrame

In [25]:
duckdb.sql("select * from new_df")

┌────────────────┬───────────┬─────────────────────────────────────────┬────────────────────┬─────────────────────────────────┬────────────┬─────────┬─────────┬────────┬─────────┐
│       id       │    cat    │                  name                   │       author       │            series_t             │ sequence_i │ genre_s │ inStock │ price  │ pages_i │
│    varchar     │  varchar  │                 varchar                 │      varchar       │             varchar             │   int64    │ varchar │ boolean │ double │  int64  │
├────────────────┼───────────┼─────────────────────────────────────────┼────────────────────┼─────────────────────────────────┼────────────┼─────────┼─────────┼────────┼─────────┤
│ 978-0641723445 │ book      │ The Lightning Thief                     │ Rick Riordan       │ Percy Jackson and the Olympians │          1 │ fantasy │ true    │   12.5 │     384 │
│ 978-1423103349 │ paperback │ The Sea of Monsters                     │ Rick Riordan       │ Percy Jackson and the Olympians │          2 │ fantasy │ true    │   6.49 │     304 │
│ 978-1857995879 │ paperback │ Sophie's World : The Greek Philosophers │ Jostein Gaarder    │ NULL                            │          1 │ fantasy │ true    │   3.07 │      64 │
│ 978-1923988177 │ paperback │ Lucene in Action, Second Edition        │ Michael McCandless │ NULL                            │          1 │ IT      │ true    │   30.5 │     475 │
│ 978-1933988077 │ paperback │ Lucene in Action, Second Edition        │ Michael McCandless │ NULL                            │          1 │ IT      │ true    │   30.5 │     475 │
│ 968-1933988177 │ paperback │ Lucene in Action, Second Edition        │ Michael McCandless │ NULL                            │          1 │ IT      │ true    │   30.5 │     300 │
│ 978-2933988077 │ paperback │ Lucene in Action, Second Edition        │ Michael McCandless │ NULL                            │          1 │ IT      │ true    │   30.5 │     475 │
└────────────────┴───────────┴─────────────────────────────────────────┴────────────────────┴─────────────────────────────────┴────────────┴─────────┴─────────┴────────┴─────────┘

Try it with Colab’s sample data

In [26]:
ans = duckdb.read_json("/content/sample_data/anscombe.json")

In [27]:
ans

┌─────────┬────────┬────────┐
│ Series  │   X    │   Y    │
│ varchar │ double │ double │
├─────────┼────────┼────────┤
│ I       │   10.0 │   8.04 │
│ I       │    8.0 │   6.95 │
│ I       │   13.0 │   7.58 │
│ I       │    9.0 │   8.81 │
│ I       │   11.0 │   8.33 │
│ I       │   14.0 │   9.96 │
│ I       │    6.0 │   7.24 │
│ I       │    4.0 │   4.26 │
│ I       │   12.0 │  10.84 │
│ I       │    7.0 │   4.81 │
│ ·       │     ·  │     ·  │
│ ·       │     ·  │     ·  │
│ ·       │     ·  │     ·  │
│ IV      │    8.0 │   5.76 │
│ IV      │    8.0 │   7.71 │
│ IV      │    8.0 │   8.84 │
│ IV      │    8.0 │   8.47 │
│ IV      │    8.0 │   7.04 │
│ IV      │    8.0 │   5.25 │
│ IV      │   19.0 │   12.5 │
│ IV      │    8.0 │   5.56 │
│ IV      │    8.0 │   7.91 │
│ IV      │    8.0 │   6.89 │
├─────────┴────────┴────────┤
│    44 rows (20 shown)     │
└───────────────────────────┘

# Write to file: Export the data as Parquet or CSV

In [ ]:
ans.to_parquet("ans1.parquet")

In [ ]:
duckdb.write_csv(ans.df(), "ans.csv")